(in-package #:adaptiv)

(defconstant +country-codes+ #.(let ((c-h (make-hash-table)))
                                 (map nil #'(lambda (x)
                                              (let ((key (car x))
                                                    (val (cdr x)))
                                               (setf (gethash (intern (symbol-name key) :keyword) c-h)
                                                     (list (string-trim " " (first val)) (second val) (string-trim " " (or (third val) ""))))))
                                      '((:AD "Andorra" 1974 " ")
                                        (:AE "United Arab Emirates" 1974 " ")
                                        (:AF "Afghanistan" 1974 " ")
                                        (:AG "Antigua and Barbuda" 1974 " ")
                                        (:AI "Anguilla" 1983 "AI previously represented French Afar and Issas ")
                                        (:AL "Albania" 1974 " ")
                                        (:AM "Armenia" 1992 " ")
                                        (:AN "Netherlands Antilles" 1974 " ")
                                        (:AO "Angola" 1974 " ")
                                        (:AQ "Antarctica" 1974 "Territories south of 60° south latitude Code taken from name in French: Antarctique") 
                                        (:AR "Argentina" 1974 " ")
                                        (:AS "American Samoa" 1974 " ")
                                        (:AT "Austria" 1974 " ")
                                        (:AU "Australia" 1974 " ")
                                        (:AW "Aruba" 1986 " ")
                                        (:AX "Aland Islands ßÅland Islands" 2004 " ")
                                        (:AZ "Azerbaijan" 1992 " ")
                                        (:BA "Bosnia and Herzegovina" 1992 " ")
                                        (:BB "Barbados" 1974 " ")
                                        (:BD "Bangladesh" 1974 " ")
                                        (:BE "Belgium" 1974 " ")
                                        (:BF "Burkina Faso" 1984 "Name changed from Upper Volta (HV) ")
                                        (:BG "Bulgaria" 1974 " ")
                                        (:BH "Bahrain" 1974 " ")
                                        (:BI "Burundi" 1974 " ")
                                        (:BJ "Benin" 1977 "Name changed from Dahomey (DY) ")
                                        (:BL "Saint Barthélemy" 2007 " ")
                                        (:BM "Bermuda" 1974 " ")
                                        (:BN "Brunei Darussalam" 1974 " ")
                                        (:BO "Bolivia, Plurinational State of" 1974 "Previous ISO country name: Bolivia (1974ó2009) ")
                                        (:BR "Brazil" 1974 " ")
                                        (:BS "Bahamas" 1974 " ")
                                        (:BT "Bhutan" 1974 " ")
                                        (:BV "Bouvet Island" 1974 " ")
                                        (:BW "Botswana" 1974 " ")
                                        (:BY "Belarus" 1974 "Code taken from previous ISO country name: Byelorussian SSR (1974ó1992) ")
                                        (:BZ "Belize" 1974 " ")
                                        (:CA "Canada" 1974 " ")
                                        (:CC "Cocos (Keeling) Islands" 1974 " ")
                                        (:CD "Congo, the Democratic Republic of the" 1997 "Name changed from Zaire (ZR) ")
                                        (:CF "Central African Republic" 1974 " ")
                                        (:CG "Congo" 1974 " ")
                                        (:CH "Switzerland" 1974 "Code taken from name in Latin: Confoederatio Helvetica ")
                                        (:CI "Cote d'Ivoire ßCôte d'Ivoire" 1974 "i.e., Ivory Coast ")
                                        (:CK "Cook Islands" 1974 " ")
                                        (:CL "Chile" 1974 " ")
                                        (:CM "Cameroon" 1974 " ")
                                        (:CN "China" 1974 " ")
                                        (:CO "Colombia" 1974 " ")
                                        (:CR "Costa Rica" 1974 " ")
                                        (:CU "Cuba" 1974 " ")
                                        (:CV "Cape Verde" 1974 " ")
                                        (:CX "Christmas Island" 1974 " ")
                                        (:CY "Cyprus" 1974 " ")
                                        (:CZ "Czech Republic" 1993 " ")
                                        (:DE "Germany" 1974 "Previous ISO country name: Germany, Federal Republic of (1974ó1990) Code taken from name in German: Deutschland ")
                                        (:DJ "Djibouti" 1977 "Name changed from French Afar and Issas (AI) ")
                                        (:DK "Denmark" 1974 " ")
                                        (:DM "Dominica" 1974 " ")
                                        (:DO "Dominican Republic" 1974 " ")
                                        (:DZ "Algeria" 1974 "Code taken from name in Kabyle: Dzayer ")
                                        (:EC "Ecuador" 1974 " ")
                                        (:EE "Estonia" 1992 "Code taken from name in Estonian: Eesti ")
                                        (:EG "Egypt" 1974 " ")
                                        (:EH "Western Sahara" 1974 "Previous ISO country name: Spanish Sahara (1974ó?) Code taken from former name in Spanish: Sahara español ")
                                        (:ER "Eritrea" 1993 " ")
                                        (:ES "Spain" 1974 "Includes Canary Islands, Ceuta and Melilla Code taken from name in Spanish: España ")
                                        (:ET "Ethiopia" 1974 " ")
                                        (:FI "Finland" 1974 " ")
                                        (:FJ "Fiji" 1974 " ")
                                        (:FK "Falkland Islands (Malvinas)" 1974 " ")
                                        (:FM "Micronesia, Federated States of" 1986 "Previous ISO country name: Micronesia (1986ó1992) ")
                                        (:FO "Faroe Islands" 1974 " ")
                                        (:FR "France" 1974 "Includes Clipperton Island ")
                                        (:GA "Gabon" 1974 " ")
                                        (:GB "United Kingdom" 1974 "Code taken from official name: United Kingdom of Great Britain and Northern Ireland")
                                        (:UK "also exceptionally reserved on request of the United Kingdom ")
                                        (:GD "Grenada" 1974 " ")
                                        (:GE "Georgia" 1992 "GE previously represented Gilbert and Ellice Islands ")
                                        (:GF "French Guiana" 1974 "Code taken from name in French: Guyane française ")
                                        (:GG "Guernsey" 2006 " ")
                                        (:GH "Ghana" 1974 " ")
                                        (:GI "Gibraltar" 1974 " ")
                                        (:GL "Greenland" 1974 " ")
                                        (:GM "Gambia" 1974 " ")
                                        (:GN "Guinea" 1974 " ")
                                        (:GP "Guadeloupe" 1974 " ")
                                        (:GQ "Equatorial Guinea" 1974 "Code taken from name in French: Guinée équatoriale ")
                                        (:GR "Greece" 1974 " ")
                                        (:GS "South Georgia and the South Sandwich Islands" 1993 " ")
                                        (:GT "Guatemala" 1974 " ")
                                        (:GU "Guam" 1974 " ")
                                        (:GW "Guinea-Bissau" 1974 " ")
                                        (:GY "Guyana" 1974 " ")
                                        (:HK "Hong Kong" 1974 " ")
                                        (:HM "Heard Island and McDonald Islands" 1974 " ")
                                        (:HN "Honduras" 1974 " ")
                                        (:HR "Croatia" 1992 "Code taken from name in Croatian: Hrvatska ")
                                        (:HT "Haiti" 1974 " ")
                                        (:HU "Hungary" 1974 " ")
                                        (:ID "Indonesia" 1974 " ")
                                        (:IE "Ireland" 1974 " ")
                                        (:IL "Israel" 1974 " ")
                                        (:IM "Isle of Man" 2006 " ")
                                        (:IN "India" 1974 " ")
                                        (:IO "British Indian Ocean Territory" 1974 "Includes Diego Garcia ")
                                        (:IQ "Iraq" 1974 " ")
                                        (:IR "Iran, Islamic Republic of" 1974 " ")
                                        (:IS "Iceland" 1974 "Code taken from name in Icelandic: Ísland ")
                                        (:IT "Italy" 1974 " ")
                                        (:JE "Jersey" 2006 " ")
                                        (:JM "Jamaica" 1974 " ")
                                        (:JO "Jordan" 1974 " ")
                                        (:JP "Japan" 1974 " ")
                                        (:KE "Kenya" 1974 " ")
                                        (:KG "Kyrgyzstan" 1992 " ")
                                        (:KH "Cambodia" 1974 "Previous ISO country name: Kampuchea (1974ó1990) Code taken from former name: Khmer Republic") 
                                        (:KI "Kiribati" 1979 " ")
                                        (:KM "Comoros" 1974 "Code taken from name in Comorian: Komori ")
                                        (:KN "Saint Kitts and Nevis" 1974 "Previous ISO country name: Saint Kitts-Nevis-Anguilla (1974ó1983) ")
                                        (:KP "Korea, Democratic People's Republic of" 1974 "i.e., North Korea ")
                                        (:KR "Korea, Republic of" 1974 "i.e., South Korea ")
                                        (:KW "Kuwait" 1974 " ")
                                        (:KY "Cayman Islands" 1974 " ")
                                        (:KZ "Kazakhstan" 1992 "Previous ISO country name: Kazakstan (1992ó2002) ")
                                        (:LA "Lao People's Democratic Republic" 1974 " ")
                                        (:LB "Lebanon" 1974 " ")
                                        (:LC "Saint Lucia" 1974 " ")
                                        (:LI "Liechtenstein" 1974 " ")
                                        (:LK "Sri Lanka" 1974 " ")
                                        (:LR "Liberia" 1974 " ")
                                        (:LS "Lesotho" 1974 " ")
                                        (:LT "Lithuania" 1992 " ")
                                        (:LU "Luxembourg" 1974 " ")
                                        (:LV "Latvia" 1992 " ")
                                        (:LY "Libyan Arab Jamahiriya" 1974 " ")
                                        (:MA "Morocco" 1974 "Code taken from name in French: Maroc ")
                                        (:MC "Monaco" 1974 " ")
                                        (:MD "Moldova, Republic of" 1992 "Previous ISO country name: Moldova (2008ó2009) ")
                                        (:ME "Montenegro" 2006 " ")
                                        (:MF "Saint Martin (French part)" 2007 " ")
                                        (:MG "Madagascar" 1974 " ")
                                        (:MH "Marshall Islands" 1986 " ")
                                        (:MK "Macedonia, the former Yugoslav Republic of" 1993 "Designated as such due to naming dispute Code taken from name in Macedonian: Makedonija ")
                                        (:ML "Mali" 1974 " ")
                                        (:MM "Myanmar" 1989 "Name changed from Burma (BU) ")
                                        (:MN "Mongolia" 1974 " ")
                                        (:MO "Macao" 1974 "Previous ISO country name: Macau (1974ó2002) ")
                                        (:MP "Northern Mariana Islands" 1986 " ")
                                        (:MQ "Martinique" 1974 " ")
                                        (:MR "Mauritania" 1974 " ")
                                        (:MS "Montserrat" 1974 " ")
                                        (:MT "Malta" 1974 " ")
                                        (:MU "Mauritius" 1974 " ")
                                        (:MV "Maldives" 1974 " ")
                                        (:MW "Malawi" 1974 " ")
                                        (:MX "Mexico" 1974 " ")
                                        (:MY "Malaysia" 1974 " ")
                                        (:MZ "Mozambique" 1974 " ")
                                        (:NA "Namibia" 1974 " ")
                                        (:NC "New Caledonia" 1974 " ")
                                        (:NE "Niger" 1974 " ")
                                        (:NF "Norfolk Island" 1974 " ")
                                        (:NG "Nigeria" 1974 " ")
                                        (:NI "Nicaragua" 1974 " ")
                                        (:NL "Netherlands" 1974 " ")
                                        (:NO "Norway" 1974 " ")
                                        (:NP "Nepal" 1974 " ")
                                        (:NR "Nauru" 1974 " ")
                                        (:NU "Niue" 1974 " ")
                                        (:NZ "New Zealand" 1974 " ")
                                        (:OM "Oman" 1974 " ")
                                        (:PA "Panama" 1974 " ")
                                        (:PE "Peru" 1974 " ")
                                        (:PF "French Polynesia" 1974 "Code taken from name in French: Polynésie française ")
                                        (:PG "Papua New Guinea" 1974 " ")
                                        (:PH "Philippines" 1974 " ")
                                        (:PK "Pakistan" 1974 " ")
                                        (:PL "Poland" 1974 " ")
                                        (:PM "Saint Pierre and Miquelon" 1974 " ")
                                        (:PN "Pitcairn" 1974 " ")
                                        (:PR "Puerto Rico" 1974 " ")
                                        (:PS "Palestinian Territory, Occupied" 1999 "Consisting of the West Bank and the Gaza Strip ")
                                        (:PT "Portugal" 1974 " ")
                                        (:PW "Palau" 1986 " ")
                                        (:PY "Paraguay" 1974 " ")
                                        (:QA "Qatar" 1974 " ")
                                        (:RE "Reunion ßRéunion" 1974 " ")
                                        (:RO "Romania" 1974 " ")
                                        (:RS "Serbia" 2006 "Code taken from official name: Republic of Serbia ")
                                        (:RU "Russian Federation" 1992 " ")
                                        (:RW "Rwanda" 1974 " ")
                                        (:SA "Saudi Arabia" 1974 " ")
                                        (:SB "Solomon Islands" 1974 "Code taken from former name: British Solomon Islands ")
                                        (:SC "Seychelles" 1974 " ")
                                        (:SD "Sudan" 1974 " ")
                                        (:SE "Sweden" 1974 " ")
                                        (:SG "Singapore" 1974 " ")
                                        (:SH "Saint Helena" 1974 "Includes Ascension Island and Tristan da Cunha ")
                                        (:SI "Slovenia" 1992 " ")
                                        (:SJ "Svalbard and Jan Mayen" 1974 "Consisting of Svalbard and Jan Mayen ")
                                        (:SK "Slovakia" 1993 "SK previously represented Sikkim ")
                                        (:SL "Sierra Leone" 1974 " ")
                                        (:SM "San Marino" 1974 " ")
                                        (:SN "Senegal" 1974 " ")
                                        (:SO "Somalia" 1974 " ")
                                        (:SR "Suriname" 1974 " ")
                                        (:ST "Sao Tome and Principe" 1974 " ")
                                        (:SV "El Salvador" 1974 " ")
                                        (:SY "Syrian Arab Republic" 1974 " ")
                                        (:SZ "Swaziland" 1974 " ")
                                        (:TC "Turks and Caicos Islands" 1974 " ")
                                        (:TD "Chad" 1974 "Code taken from name in French: Tchad ")
                                        (:TF "French Southern Territories" 1979 "Covers the jurisdiction of the French Southern and Antarctic Lands except Adélie Land Code taken from name in French: Terres australes françaises") 
                                        (:TG "Togo" 1974 " ")
                                        (:TH "Thailand" 1974 " ")
                                        (:TJ "Tajikistan" 1992 " ")
                                        (:TK "Tokelau" 1974 " ")
                                        (:TL "Timor-Leste" 2002 "Name changed from East Timor (TP) ")
                                        (:TM "Turkmenistan" 1992 " ")
                                        (:TN "Tunisia" 1974 " ")
                                        (:TO "Tonga" 1974 " ")
                                        (:TR "Turkey" 1974 " ")
                                        (:TT "Trinidad and Tobago" 1974 " ")
                                        (:TV "Tuvalu" 1979 " ")
                                        (:TW "Taiwan, Province of China" 1974 "Covers the jurisdiction of the Republic of China except Kinmen and Lienchiang Designated as such due to its political status within the UN") 
                                        (:TZ "Tanzania, United Republic of" 1974 " ")
                                        (:UA "Ukraine" 1974 "Previous ISO country name: Ukrainian SSR (1974ó1992) ")
                                        (:UG "Uganda" 1974 " ")
                                        (:UM "United States Minor Outlying Islands" 1986 "Consisting of Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Islands, Navassa Island, Palmyra Atoll, and Wake Island ")
                                        (:US "United States" 1974 " ")
                                        (:UY "Uruguay" 1974 " ")
                                        (:UZ "Uzbekistan" 1992 " ")
                                        (:VA "Holy See (Vatican City State)" 1974 "Territory of the Holy See Previous ISO country name: Vatican City State (Holy See) (1974ó1996)")
                                        (:VC "Saint Vincent and the Grenadines" 1974 " ")
                                        (:VE "Venezuela, Bolivarian Republic of" 1974 "Previous ISO country name: Venezuela (1974ó2009) ")
                                        (:VG "Virgin Islands, British" 1974 " ")
                                        (:VI "Virgin Islands, U.S." 1974 " ")
                                        (:VN "Viet Nam" 1974 " ")
                                        (:VU "Vanuatu" 1980 "Name changed from New Hebrides (NH) ")
                                        (:WF "Wallis and Futuna" 1974 " ")
                                        (:WS "Samoa" 1974 "Code taken from former name: Western Samoa ")
                                        (:YE "Yemen" 1974 "Previous ISO country name: Yemen, Republic of (1990ó1993) ")
                                        (:YT "Mayotte" 1993 " ")
                                        (:ZA "South Africa" 1974 "Code taken from name in Dutch: Zuid-Afrika ")
                                        (:ZM "Zambia" 1974 " ")
                                        (:ZW "Zimbabwe" 1980 "Name changed from Southern Rhodesia (RH) ")
                                        (:AC "Ascension Island" nil "Reserved on request of UPU Currently used for the ccTLD .ac")
                                        (:CP "Clipperton Island" nil "Reserved on request of ITU") 
                                        (:DG "Diego Garcia" nil "Reserved on request of ITU") 
                                        (:EA "Ceuta, Melilla" nil "Reserved on request of WCO to represent area outside EU customs territory") 
                                        (:EU "European Union" nil "Originally reserved on request of ISO 4217/MA to provide country code for Euro Extended for use in ISO 6166 \"Securities ó International securities identification numbering system (ISIN)\" in 1998-03 Extended for any application needing to represent the name European Union in 1999-08 Currently used for the ccTLD .eu") 
                                        (:FX "France, Metropolitan" nil "Officially assigned 1993-06-18ó1997-07-14 Reserved on request of France") 
                                        (:IC "Canary Islands" nil "Reserved on request of WCO to represent area outside EU customs territory") 
                                        (:SU "USSR" nil "Officially assigned 1974ó1992-08-30 Transitionally reserved 1992-09ó2008-06 Currently used for the ccTLD .su") 
                                        (:TA "Tristan da Cunha" nil "Reserved on request of UPU") 
                                        (:UK "United Kingdom" nil "Reserved on request of the United Kingdom Currently used for the ccTLD .uk, and by the European Commission")
                                        (:AX "Aland" 2004-02-13 "Reserved on request of Finland")
                                        (:GG "Guernsey" 2006-03-29 "Reserved on request of UPU Used for the ccTLD .gg when reserved") 
                                        (:IM "Isle of Man" 2006-03-29 "Reserved on request of UPU Used for the ccTLD .im when reserved") 
                                        (:JE "Jersey" 2006-03-29 "Reserved on request of UPU Used for the ccTLD .je when reserved" )
                                        (:BU "Burma" 1989-12)  
                                        (:CS "Serbia and Montenegro" 2006-09 "CS previously represented Czechoslovakia") 
                                        (:NT "Neutral Zone" 1993-07)  
                                        (:SF "Finland" 1995-09 "Finland officially uses the code FI. Previously used in international postal codes and vehicle registration codes. Code stands for Suomi Finland (Suomi is the Finnish name of the country)") 
                                        (:TP "East Timor" 2002-05 "Currently used for the ccTLD .tp") 
                                        (:YU "Yugoslavia" 2003-07 "Currently used for the ccTLD .yu") 
                                        (:ZR "Zaire" 1997-07)))
                                 c-h))
(defconstant +currency-codes+ #.(let ((c-h (make-hash-table)))
                                  (map nil #'(lambda (cur)
                                               (let ((key (car cur))
                                                     (val (cdr cur)))
                                                 (setf (gethash (car cur) c-h)
                                                       (mapcar #'(lambda (item)
                                                                   (typecase item
                                                                     (string (string-trim " " item))
                                                                     (t item)))
                                                               (cdr cur)))))
                                       ;;(:key Country Units Symbol . Basis)
                                       '((:AED :AE "Dirhams ")
                                         (:AFA :AF "Afghani")
                                         (:AFN :AF "Afghanis ")
                                         (:ALL :AL "Leke ")
                                         (:AMD :AM "Drams ")
                                         (:ANG :AN "Guilders (also called Florins) " "NAf")
                                         (:AOA :AO "Kwanza ")
                                         (:AON :AO "New Kwanza")
                                         (:ARP :AR "Peso (-> ARS)")
                                         (:ARS :AR "Pesos ")
                                         (:ATS :AT "Schilling" NIL "ACT/360")
                                         (:AUD :AU "Dollars " "$" "ACT/365")
                                         (:AWF :AW "Florin")
                                         (:AWG :AW "Guilders (also called Florins) " "f")
                                         (:AZM :AZ "Manat")
                                         (:AZN :AZ "New Manats ")
                                         (:BAK :BA "Convertible mark")
                                         (:BAM :BA "Convertible Marka " "KM")
                                         (:BBD :BB "Dollars " "Bds$")
                                         (:BDT :BD "Taka ")
                                         (:BEF :BE "Franc" NIL "ACT/360")
                                         (:BGN :BG "Leva ")
                                         (:BHD :BH "Dinars ")
                                         (:BIF :BI "Francs " "FBu")
                                         (:BMD :BM "Dollars " "BD$")
                                         (:BND :BN "Dollars " "B$")
                                         (:BOB :BO "Bolivianos " "Bs.")
                                         (:BRL :BR "Brazil Real " "R$")
                                         (:BRR :BR "Brazilian Real (-> BRL)")
                                         (:BSD :BS "Dollars " "B$")
                                         (:BTN :BT "Ngultrum " "Nu.")
                                         (:BTR :BT "Rupee")
                                         (:BWP :BW "Pulas " "P")
                                         (:BYR :BY "Rubles " "Br")
                                         (:BZD :BZ "Dollars " "BZ$")
                                         (:CAD :CA "Dollars " "$" "ACT/365")
                                         (:CDF :CD "Congolese Francs " "F")
                                         (:CHF :CH "Francs " "Fr." "ACT/360")
                                         (:CLP :CL "Pesos " "$")
                                         (:CNY :CN "Yuan Renminbi " "245")
                                         (:COP :CO "Pesos " "Col$")
                                         (:CRC :CR "Colones " "C")
                                         (:CUP :CU "Pesos ")
                                         (:CVE :CV "Escudos " "Esc")
                                         (:CYP :CY "Pounds (expires 2008-Jan-31) ")
                                         (:CZK :CZ "Koruny " "Kc")
                                         (:DEM :DE "Deutsche Mark" NIL "ACT/360")
                                         (:DJF :DJ "Francs " "Fdj")
                                         (:DKK :DK "Kroner " "Kr")
                                         (:DOP :DO "Pesos " "RD$")
                                         (:DZD :DZ "Algeria Dinars ")
                                         (:ECS :EC "Sucre")
                                         (:EEK :EE "Krooni " "KR")
                                         (:EGP :EG "Pounds " (STRING #\POUND_SIGN))
                                         (:ERN :ER "Nakfa " "Nfa")
                                         (:ESP :ES "Peseta" NIL "ACT/360")
                                         (:ETB :ET "Birr " "Br")
                                         (:EUR :EU "Euro " (STRING #\EURO_SIGN) "ACT/360")
                                         (:FIM :SF "Markka")
                                         (:FJD :FJ "Dollars " "FJ$")
                                         (:FKP :FK "Pounds " (STRING #\POUND_SIGN))
                                         (:FRF :FR "Franc" NIL "ACT/360")
                                         (:GBP :UK "Pounds " (STRING #\POUND_SIGN) "ACT/365")
                                         (:GEL :GE "Lari ")
                                         (:GGP :GG "Pounds ")
                                         (:GHC :GH "Cedi")
                                         (:GHS :GH "Cedis ")
                                         (:GIP :GI "Pounds " (STRING #\POUND_SIGN))
                                         (:GMD :GM "Dalasi " "D")
                                         (:GNF :GN "Francs " "FG")
                                         (:GRD :GR "Drachma")
                                         (:GTQ :GT "Quetzales " "Q")
                                         (:GYD :GY "Dollars " "GY$")
                                         (:HKD :HK "Dollars " "HK$" "ACT/ACT")
                                         (:HNL :HN "Lempiras " "L")
                                         (:HRK :HR "Kuna " "kn")
                                         (:HTG :HT "Gourdes " "G")
                                         (:HUF :HU "Forint " "Ft")
                                         (:IDR :ID "Rupiahs " "Rp")
                                         (:IEP :IE "Punt")
                                         (:ILS :IL "New Shekels ")
                                         (:IMP :IM "Pounds ")
                                         (:INR :IN "Rupees " "Rs")
                                         (:IQD :IQ "Dinars ")
                                         (:IRR :IR "Rials ")
                                         (:ISK :IS "Kronur " "kr")
                                         (:ITL :IT "Lira" NIL "ACT/360")
                                         (:JEP :JE "Pounds ")
                                         (:JMD :JM "Dollars " "J$")
                                         (:JOD :JO "Dinars ")
                                         (:JPY :JP "Yen " (STRING #\YEN_SIGN) "ACT/365")
                                         (:KES :KE "Shillings " "KSh")
                                         (:KGS :KG "Soms ")
                                         (:KHR :KH "Riels ")
                                         (:KMF :KM "Francs ")
                                         (:KPW :KP "Won " "W")
                                         (:KRW :KR "Won " "W")
                                         (:KWD :KW "Dinars ")
                                         (:KYD :KY "Dollars " "KY$")
                                         (:KZT :KZ "Tenge " "T")
                                         (:LAK :LA "Kips " "KN")
                                         (:LBP :LB "Pounds ")
                                         (:LKR :LK "Rupees " "Rs")
                                         (:LRD :LR "Dollars " "L$")
                                         (:LSL :LS "Maloti " "M")
                                         (:LTL :LT "Litai " "Lt")
                                         (:LUF :LU "Franc")
                                         (:LVL :LV "Lati " "Ls")
                                         (:LYD :LY "Dinars " "LD")
                                         (:MAD :MA "Dirhams ")
                                         (:MDL :MD "Lei ")
                                         (:MGA :MG "Ariary " "FMG")
                                         (:MGF :MG "Malagasy Franc")
                                         (:MKD :MK "Denars ")
                                         (:MMK :MM "Kyats " "K")
                                         (:MNT :MN "Tugriks " "T")
                                         (:MOP :MO "Patacas " "P")
                                         (:MRO :MR "Ouguiyas " "UM")
                                         (:MTL :MT "Liri (expires 2008-Jan-31) ")
                                         (:MUR :MU "Rupees " "Rs")
                                         (:MVR :MV "Rufiyaa " "Rf")
                                         (:MWK :MW "Kwachas " "MK")
                                         (:MXN :MX "Pesos " "$")
                                         (:MYR :MY "Ringgits " "RM")
                                         (:MZM :MZ "Metical" "MTn")
                                         (:MZN :MZ "Meticais ")
                                         (:NAD :NA "Dollars " "N$")
                                         (:NGN :NG "Nairas " "N")
                                         (:NIO :NI "Cordobas " "C$")
                                         (:NLG :NL "Guilder" NIL "ACT/360")
                                         (:NOK :NO "Krone " "kr")
                                         (:NPR :NP "Nepal Rupees " "NRs")
                                         (:NZD :NZ "Dollars " "NZ$")
                                         (:OMR :OM "Rials ")
                                         (:PAB :PA "Balboa " "B./")
                                         (:PEN :PE "Nuevos Soles " "S/.")
                                         (:PGK :PG "Kina " "K")
                                         (:PHP :PH "Pesos " "321")
                                         (:PKR :PK "Rupees " "Rs.")
                                         (:PLN :PL "Zlotych ")
                                         (:PTE :PT "Escudo")
                                         (:PYG :PY "Guarani ")
                                         (:QAR :QA "Rials " "QR")
                                         (:ROL :RO "Leu")
                                         (:RON :RO "New Lei " "L")
                                         (:RSD :RS "Dinars " "din.")
                                         (:RUB :RU "Rubles " "R")
                                         (:RWF :RW "Rwanda Francs " "RF")
                                         (:SAR :SA "Riyals " "SR")
                                         (:SBD :SB "Dollars " "SI$")
                                         (:SCR :SC "Rupees " "SR")
                                         (:SDD :SD "Dinar (-> SDP)")
                                         (:SDG :SD "Pounds ")
                                         (:SDP :SD "Dinar (-> SDD)")
                                         (:SEK :SE "Kronor " "kr" "ACT/360")
                                         (:SGD :SG "Dollars " "S$" "ACT/365")
                                         (:SHP :SH "Pounds " "243")
                                         (:SIT :SI "Tolar")
                                         (:SKK :SK "Koruna")
                                         (:SLL :SL "Leones " "Le")
                                         (:SOS :SO "Shillings " "Sh.")
                                         (:SPL NIL "Luigini ")
                                         (:SRD :SR "Dollars " "$")
                                         (:SRG :SR "Guilder")
                                         (:STD :ST "Dobras " "Db")
                                         (:SVC :SV "Colones ")
                                         (:SYP :SY "Pounds ")
                                         (:SZL :SZ "Emalangeni " "E")
                                         (:THB :TH "Baht " "B")
                                         (:TJR :TJ "Ruble")
                                         (:TJS :TJ "Somoni ")
                                         (:TMM :TM "Manats ")
                                         (:TND :TN "Dinars " "DT")
                                         (:TOP :TO "Pa'anga ")
                                         (:TRY :TR "New Lira " "YTL")
                                         (:TTD :TT "Dollars " "TT$")
                                         (:TVD :TV "Tuvalu Dollars ")
                                         (:TWD :TW "New Dollars " "NT$")
                                         (:TZS :TZ "Shillings ")
                                         (:UAH :UA "Hryvnia ")
                                         (:UGX :UG "Shillings " "USh")
                                         (:USD :US "Dollars " "US$" "ACT/360")
                                         (:UYU :UY "Pesos " "$U")
                                         (:UZS :UZ "Sums ")
                                         (:VEB :BO "Bolivares (expires 2008-Jun-30) " "Bs")
                                         (:VEF :BO "Bolivares Fuertes ")
                                         (:VND :VN "Dong " "d")
                                         (:VUV :VU "Vatu " "VT")
                                         (:WST :WS "Tala " "WS$")
                                         (:XAF "Communaut351 Financi350re Africaine BEAC" "Francs " "CFA")
                                         (:XAG "Silver" "Ounces ")
                                         (:XAU "Gold" "Ounces ")
                                         (:XCD "East Caribbean" "Dollars" "EC$")
                                         (:XDR "International Monetary Fund (IMF) Special Drawing Rights" "SDR")
                                         (:XOF "Communaut351 Financi350re Africaine BCEAO" "Francs " "CFA")
                                         (:XPD "Palladium" "Ounces")
                                         (:XPF "Comptoirs Fran347ais du Pacifique Francs" "F")
                                         (:XPT "Platinum" "Ounces")
                                         (:YER :YE "Rials ")
                                         (:YUN :YU "New Dinar")
                                         (:ZAR :ZA "Rand " "R")
                                         (:ZMK :ZM "Kwacha " "ZK")
                                         (:ZRN :ZR "New Zaire")
                                         (:ZWD :ZW "Zimbabwe Dollars ")))
                                  c-h))
(flet ((to-keyword (cur)
         (typecase cur
           (keyword cur)
           ((or string symbol) (intern (string-upcase cur) :keyword)))))
  (defun get-currency (cur)
    (gethash (to-keyword cur) +currency-codes+ '(nil nil nil nil)))
  (defun get-country (iso-code)
    (gethash (to-keyword iso-code) +country-codes+)))
(defun get-country-code-from-currency-code (currency-code)
  (car (get-currency currency-code)))
(defun get-currency-code-from-country-code (iso-code)
  (maphash (lambda (key val)
             (when (eql iso-code (car val))
               (return-from get-currency-code-from-country-code key)))
           +currency-codes+))
(defun get-currency-name-from-code (code)
  (string-trim " " (second (get-currency code))))
(defun get-currency-symbol-from-code (code)
  (string-trim " " (or (third (get-currency code))
                       "")))

(defun get-country-name-from-code (iso-code)
  (car (get-country iso-code)))
(defun get-country-code-from-name (country-name)
  (maphash (lambda (key val)
             (when (string= (string-upcase country-name) (string-upcase (car val)))
               (return-from get-country-code-from-name key)))
           +country-codes+))




(defconstant +day-count-conventions+ #.(make-map '()))